apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "anything-llm.fullname" . }}-config
  labels:
    {{- include "anything-llm.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: "{{ $value }}"
{{- end }}
