apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "anything-llm.fullname" . }}
  labels:
    {{- include "anything-llm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "anything-llm.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "anything-llm.selectorLabels" . | nindent 8 }}
      annotations:
        roll: {{ now | date "2006-01-02T15:04:05Z07:00" }}
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: {{ include "anything-llm.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "anything-llm.fullname" . }}-config
          {{- if .Values.secret.enabled }}
            - secretRef:
                name: {{ include "anything-llm.fullname" . }}-secret
          {{- end }}
          volumeMounts:
            {{- range .Values.persistence.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              add:
                - SYS_ADMIN
      volumes:
        {{- range .Values.persistence.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
        {{- end }}
      restartPolicy: Always
