{{- range .Values.persistence.volumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  labels:
    {{- include "anything-llm.labels" $ | nindent 4 }}
spec:
  accessModes:
    - {{ $.Values.persistence.accessMode }}
  storageClassName: {{ $.Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ $.Values.persistence.size }}
---
{{- end }}
